services:
    _defaults:
        autowire: true
        autoconfigure: true

    slope_it.breadcrumb.listener:
        class: SlopeIt\BreadcrumbBundle\EventListener\BreadcrumbListener

    slope_it.breadcrumb.builder:
        class: SlopeIt\BreadcrumbBundle\Service\BreadcrumbBuilder

    slope_it.breadcrumb.item_processor:
        class: SlopeIt\BreadcrumbBundle\Service\BreadcrumbItemProcessor

    slope_it.breadcrumb.twig_extension:
        class: SlopeIt\BreadcrumbBundle\Twig\BreadcrumbExtension
        arguments:
            $template: '%slope_it_breadcrumb.template%'

    # Alias services with their FQCN, so that they can be injected without specifying their alias.
    SlopeIt\BreadcrumbBundle\EventListener\BreadcrumbListener:
        alias: slope_it.breadcrumb.listener

    SlopeIt\BreadcrumbBundle\Service\BreadcrumbBuilder:
        alias: slope_it.breadcrumb.builder

    SlopeIt\BreadcrumbBundle\Service\BreadcrumbItemProcessor:
        alias: slope_it.breadcrumb.item_processor

    SlopeIt\BreadcrumbBundle\Twig\BreadcrumbExtension:
        alias: slope_it.breadcrumb.twig_extension
