services:
    slope_it.breadcrumb.listener:
        class: SlopeIt\BreadcrumbBundle\EventListener\BreadcrumbListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments:
            - '@slope_it.breadcrumb.builder'
            - '@annotation_reader'

    slope_it.breadcrumb.builder:
        class: SlopeIt\BreadcrumbBundle\Service\BreadcrumbBuilder
        arguments:
            - '@slope_it.breadcrumb.item_factory'

    slope_it.breadcrumb.item_factory:
        class: SlopeIt\BreadcrumbBundle\Service\BreadcrumbItemFactory

    slope_it.breadcrumb.item_processor:
        class: SlopeIt\BreadcrumbBundle\Service\BreadcrumbItemProcessor
        arguments:
            - '@property_accessor'
            - '@translator'
            - '@router'
            - '@request_stack'

    slope_it.breadcrumb.twig_extension:
        class: SlopeIt\BreadcrumbBundle\Twig\BreadcrumbExtension
        arguments:
            - '@slope_it.breadcrumb.builder'
            - '@slope_it.breadcrumb.item_processor'
            - '%slope_it_breadcrumb.template%'
        tags:
            - { name: twig.extension }
